"""Interactive setup wizard — runs when no .env file exists."""

import os
import sys
from pathlib import Path

ENV_PATH = Path(__file__).resolve().parent.parent / ".env"


def env_exists() -> bool:
    """Check if .env exists OR if config is already provided externally."""
    if ENV_PATH.exists() and ENV_PATH.stat().st_size > 0:
        return True
    # Skip wizard if running in a container with env vars already set
    if os.environ.get("AZURE_SPEECH_ENDPOINT") or os.environ.get("SKIP_SETUP_WIZARD"):
        return True
    # Skip if not running in a terminal (e.g., pytest, Docker, CI)
    if not sys.stdin.isatty():
        return True
    return False


def run_setup_wizard() -> None:
    """Prompt the user for configuration and write .env file."""
    print("\n" + "=" * 60)
    print("  🎙️  STT Comparison Tool — First-Time Setup")
    print("=" * 60)
    print("\nNo .env file found. Let's configure your Azure services.\n")

    lines: list[str] = [
        "# STT Comparison Tool — Generated by setup wizard\n",
    ]

    # --- Auth mode ---
    print("Authentication mode:")
    print("  1. Managed Identity (DefaultAzureCredential) — recommended")
    print("  2. API Key based authentication")
    auth_choice = _ask("Choose [1/2]", default="1")
    use_keys = auth_choice.strip() == "2"

    if use_keys:
        lines.append("# Authentication: API key mode\n")
    else:
        lines.append("# Authentication: Managed Identity (DefaultAzureCredential)\n")

    # --- Azure Speech (STT Batch, Fast) ---
    print("\n--- Azure Speech Services (STT Batch, STT Fast) ---")
    speech_endpoint = _ask(
        "Speech endpoint (custom subdomain URL)",
        hint="https://my-resource.cognitiveservices.azure.com/",
    )
    speech_region = _ask("Speech region", default="swedencentral")
    lines.append(f"\nAZURE_SPEECH_ENDPOINT={speech_endpoint}")
    lines.append(f"AZURE_SPEECH_REGION={speech_region}")
    if use_keys:
        speech_key = _ask("Speech API key")
        lines.append(f"AZURE_SPEECH_KEY={speech_key}")

    # --- MAI-Transcribe-1 + LLM Speech ---
    print("\n--- MAI-Transcribe-1 / LLM Speech (separate resource) ---")
    mai_endpoint = _ask(
        "MAI Speech endpoint",
        hint="https://foundry-mai-transcribe.cognitiveservices.azure.com/",
    )
    mai_region = _ask("MAI Speech region", default="eastus")
    lines.append(f"\nMAI_SPEECH_ENDPOINT={mai_endpoint}")
    lines.append(f"MAI_SPEECH_REGION={mai_region}")
    if use_keys:
        mai_key = _ask("MAI Speech API key", default="")
        if mai_key:
            lines.append(f"MAI_SPEECH_KEY={mai_key}")

    # --- Whisper ---
    print("\n--- Whisper (batch transcription, separate resource) ---")
    whisper_endpoint = _ask(
        "Whisper Speech endpoint",
        hint="https://my-whisper-resource.cognitiveservices.azure.com/",
    )
    whisper_region = _ask("Whisper Speech region", default="eastus")
    whisper_model_id = _ask("Whisper model ID (leave empty for auto-discovery)", default="")
    lines.append(f"\nWHISPER_SPEECH_ENDPOINT={whisper_endpoint}")
    lines.append(f"WHISPER_SPEECH_REGION={whisper_region}")
    if whisper_model_id:
        lines.append(f"AZURE_WHISPER_MODEL_ID={whisper_model_id}")
    if use_keys:
        whisper_key = _ask("Whisper Speech API key", default="")
        if whisper_key:
            lines.append(f"WHISPER_SPEECH_KEY={whisper_key}")

    # --- Azure Blob Storage ---
    print("\n--- Azure Blob Storage (used by STT Batch + Whisper) ---")
    storage_account = _ask("Storage account name", hint="mystorageaccount")
    storage_container = _ask("Storage container name", default="transcription-audio")
    lines.append(f"\nAZURE_STORAGE_ACCOUNT_NAME={storage_account}")
    lines.append(f"AZURE_STORAGE_CONTAINER_NAME={storage_container}")
    if use_keys:
        storage_conn = _ask("Storage connection string (leave empty to skip)", default="")
        if storage_conn:
            lines.append(f"AZURE_STORAGE_CONNECTION_STRING={storage_conn}")

    # --- Azure OpenAI ---
    print("\n--- Azure OpenAI (GPT-4o-transcribe) ---")
    openai_endpoint = _ask(
        "OpenAI endpoint",
        hint="https://my-resource.openai.azure.com/",
    )
    openai_deployment = _ask("OpenAI deployment name", default="gpt-4o-transcribe")
    lines.append(f"\nAZURE_OPENAI_ENDPOINT={openai_endpoint}")
    lines.append(f"AZURE_OPENAI_DEPLOYMENT_NAME={openai_deployment}")
    if use_keys:
        openai_key = _ask("OpenAI API key", default="")
        if openai_key:
            lines.append(f"AZURE_OPENAI_API_KEY={openai_key}")

    # --- Voxtral ---
    print("\n--- Voxtral Mini via Azure Foundry (optional) ---")
    voxtral_url = _ask("Voxtral endpoint URL (leave empty to skip)", default="")
    if voxtral_url:
        lines.append(f"\nVOXTRAL_ENDPOINT_URL={voxtral_url}")
        if use_keys:
            voxtral_key = _ask("Voxtral endpoint key", default="")
            if voxtral_key:
                lines.append(f"VOXTRAL_ENDPOINT_KEY={voxtral_key}")

    # Write .env
    lines.append("")  # trailing newline
    ENV_PATH.write_text("\n".join(lines))

    print(f"\n✅ Configuration saved to {ENV_PATH}")
    print("   You can edit this file anytime to update settings.\n")


def _ask(prompt: str, default: str = "", hint: str = "") -> str:
    """Prompt user for input with optional default and hint."""
    parts = [f"  {prompt}"]
    if hint:
        parts.append(f" (e.g., {hint})")
    if default:
        parts.append(f" [{default}]")
    parts.append(": ")
    value = input("".join(parts)).strip()
    return value or default
